global using Microsoft.AspNetCore.StaticFiles;
global using Microsoft.AspNetCore.Mvc;
global using System.Security.Claims;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using Microsoft.AspNetCore.Authorization;
global using TodoApi.Models;
global using System.Text;